# These are the words that will fine players to say.
swearwords:
  - Fuck
  - Bitch
  - Ass
  - Shit
  - Cunt
  - AddWords

# How much players will be charged for swearing
# You need to add .00
cost: 50.00

message: "&aYou were charged $%cost% for swearing %amount% times."
# Variables you can use:
# %player% = Player name
# %cost% = How much they are fined for swearing.
# %amount% = How many times they swore.
